CREATE USER JAVAWEB IDENTIFIED BY JAVAWEB;
GRANT CONNECT, RESOURCE TO JAVAWEB;

CREATE TABLE TBL_MEMBER(
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PWD VARCHAR2(10) NOT NULL,
    USER_NAME VARCHAR2(50),
    USER_EMAIL VARCHAR2(30) NOT NULL,
    USER_JOINDATE DATE default SYSDATE
     
);

DESC T_MEMBER;

INSERT INTO T_MEMBER
VALUES ('hong', '1212', '홍길동', 'hong@gmail.com', sysdate);
INSERT INTO T_MEMBER
VALUES ('lee', '1212', '이순신', 'lee@gmail.com', sysdate);
INSERT INTO T_MEMBER
VALUES ('kim', '1212', '김유신', 'kim@gmail.com', sysdate);

commit;
